image: alpine/3.14
packages:
  - nodejs
secrets:
  - 90412a77-7bc1-4bc2-891f-519bae9c7c11
tasks:
  - clone: |
      git clone --mirror https://git.sr.ht/~creatable/sperm
  - add-host: |
      ssh-keyscan -t rsa -H github.com >> ~/.ssh/known_hosts
  - push: |
      cd sperm.git
      git push --mirror git@github.com:Cumcord/sperm.git
